### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by laszlojasko** [VermontCoder/read_sbus#1]
In PiScope I get about 12 sbus signals in a second, but for some reason, this library lags a lot, like 1-2 seconds before it realizes the sbus signal change. Like playing an FPS game with 2000ms pings. Can you do something about it? Maybe a better algorythm?

**Comment by VermontCoder** [comment]
Hello lackoder,

I do not experience this problem when I run the code as I demonstrated in the linked video - when I manipulate the remote control the lights and servo on the pi react more or less instantly as least as far as humans can perceive.

Not sure what would be causing the delay on your end. Have you run curses based test code to see if there is a delay in the response of that? Not sure if perhaps your Pi is loaded down with some other processes; perhaps PiScope is loading the pi?

I am not sure what would be creating the delay for you.

**Comment by laszlojasko** [comment]
Hey VermontCoder,

I saw your video , that is why I am here :)

I am running it on a RPi4B with 4GB RAM, the piscope was not running at the time of the test. I just fired up piscope to have a look on the channel signal - I connected it to UART0/RX pin GPIO15. The PiScope is showing stabile receiving of signals, as mentioned 12 buckets of data per second, but the code is not respecting it, turning it into 2 sec delay for some reason. I am developing an RC/AI controlled car, and I am using the controller I got for my DJI Avata, which is an DJI Remote Controller 2 and the receiver unit is a DJI Air Unit O3. The S.bus signal comes from the yellow and brown cable of the air unit, and it is officially an s.bus cable, betaflight firmwares are reading it correctly. But betaflight is huge and C language code, and I want to use python as for AI development it is a better choice.

So.. the Pi device is not overloaded or anything, the CPU is 1-2% during the tests showed in the Task Manager also.

After having a look on the output of piscope, it turns out that the signal from the AU (Air Unit) is much shorter than 5 seconds commented in your code. I tried to set this to 2500 and 3000, but none of them worked, still lags a lot. Lagging is a huge issue for me, because I can not control the car at the moment. I tried the same code with an XBOX controller (+bluetooth), and it worked perfect, the car turns real time. But I can not use that as bluetooth have a range of 15 meters or so, and the car is a 1:10 TT-02, so the fun of RC controllign a car would last for 1-2 seconds until it gets out of reach of the bluetooth signal, so that is why I want to use the s.bus with DJI RC. So I will be able to control the car until I get a stable algorythm for the AI and drive it self, plus it is a fun to drive the car myself if I want.

I know your code works, because even lags big time, I could read values from the controller channels and match the switches and sticks with channels. Only, I need your help to make it real time based.

How can I help you to analyze the problem? Uploading a few screenshots from piscope helps? Or the code? I would do anything to make it work.

The curses display shows the same lagging.

**Comment by laszlojasko** [comment]
I shared a folder with you with images from the hardware setup to see my project and PiScope photo that may help you. [PiCar](http://gofile.me/46v6w/icFSbMAUR)

**Comment by VermontCoder** [comment]
Laszlo I'm sorry I don't have an explanation for the delay. I don't think its coming from my code, it doesn't hang up on processing the packets like this. I was running this on a Pi 3b (I think) but that shouldn't matter. If you are seeing the same delay using the curses code then its not your code either. The only other thing I can think of is changing the GPIO port to 4; your pi scope traces are on 15, which is also used for the serial interface (I think) which might be messing with it? But the traces you are getting are clean so not sure, but its the only thing I can think of.

Without being able to reproduce the error its challenging to troubleshoot this.

**Comment by laszlojasko** [comment]
Hm... interesting. But then what can cause this? I mean, if piscope can read the signal in a timely manner, why your code can not? I have been reading your code for days, not too easy for me to understand, there is some math in it :) I clearly understand the packet format. Is it not possible to use another function from pigpio to solve this? I was thinking of maybe piscope uses a different approach.. maybe it is the callback? Hmm... maybe serial_bit_bang or some other? To be honest, I must solve this, I spent too much money on this project already, it is going to be a job interview "what I can do" project. I am trying to modify your code, but I can not understand everything yet unfortunately. I am thinking of some logic I could use to detect the bit-stream better, I think the delay is caused by or the _on_update callback not firing correctly or the timing somehow is bad and not capturing the frames in the just good time.

Your toughts?

I will change pin to GPIO4 now, let's see...

**Comment by laszlojasko** [comment]
On Pin RX (GPIO) packet age is sometimes 2500 and over! but also most of the time it is in 400-1000 range, I think that causes the delay. Maybe the 3000 uS DJI frame is too short for the sbus code to detect in time? Hmmm...

Just tested, same thing happens on Pin 4. So it is not the pin selection causing this.

**Comment by laszlojasko** [comment]
I have uploaded a video also, please have a look. There I am running the curses library: IMG_5833.MOV

I see that the values are updated when the packet age resets to zero.. can we not make it somehow reset more frequently?

**Comment by VermontCoder** [comment]
I took another look at the PiScope traces. There is a very long time between packets, around 80ms. That's pretty bad latency, even if you could read them instantly. In my setup, it was usually around 6ms.

I took a look in the forums and there was something about "sbus fast" transmission. You could try looking at that. I think you'd set this through betaflight? Found this: https://david840709.gitbook.io/transtec/tech/untitled

To adapt to these long periods between packets you could try setting the _PACKET_BOUNDRY_TIME  to being something like 75_000. This parameter sets how much time the  though it shouldn't really matter as there is nothing being transmitted during this time- These are MICROseconds, so .001 millisecond.

Another thing to look at is the sampling rate of the pigpiod. Maybe increase that?

Another possibility is that this is not actually control data from the transmitter but *telemetry* data coming across on sbus. You said you see the values change with the transmitter, but perhaps it was changes in telemetry data you are seeing. The control data might be coming in on other wires, other protocols?

**Comment by VermontCoder** [comment]
There also might be other parameters you could tweak on the airunit which might get you more packets/sec.

**Comment by laszlojasko** [comment]
I did that change you mentioned, switched to Fast S.bus.. I don't see to much change in the signal frequency, do you?

I see the signal is double faster to receive a packet, 1500ms instead of 3000ms, which is correct, fast s.bus is 200k baud by specification, while normal s.bus is 100k. But the packet frequency is the same. It can be setup in the google, so I did that, was not aware of it, thanks. So.. at least we have now a faster packet reading.

PiScope003-ZoomedIn-FastSbus.png
PiScope004-ZoomedOut-FastSbus.png
PiScope005-ZoomedMid-FastSbus.png

It means at least the Rpi is capable of receiving fast s.bus.. is your code capable of receiving fast s.bus too you think? It is now less than 2ms to frame a packet, wow.

**Comment by laszlojasko** [comment]
Ok, so.. in piscope I do see the faster baud rate signal, but read_sbus_from_GPIO.py is not capable of reading it. I changed the _PACKET_BOUNDRY_TIME = 75000 but it didn't help with faster baud rate. Unfortunately, I can only use your library to read the normal baud rate sbus signal. Which is fine I guess for now. if I could read the sbus every 80ms, it would be great for a start, but I hae no idea why I get 300-2000ms..

update: wow, changing to fast s.bus and reverting to normal baud rate in the googles, resulted in some change: packet times are now under 100ms! I hope this will remain like this... will let you know. Maybe it is a bug??

**Comment by laszlojasko** [comment]
S.bus delay issue seems to solving.. if I turned on the DJI Googles 2, the s.bus signal goes very fast in normal mode, never above 200, most of the time under 100. It seems the Air Unit switches to faster s.bus and more reactive once it connect to the googles. So your code seem to work fine :) wohooo! Only I will need the googles with me all the time on the field to test the car with.

**Comment by laszlojasko** [comment]
Ah, I can not reproduce it again.. the fast signal receiving... somewhere there is something that slows down things... I have no idea what is this! But anyway, in fast sbus mode, your code is just not working, doesn't capture any packet with 200k baud rate.

**Comment by VermontCoder** [comment]
Laszlo, If the packets are coming every 2ms, you need to modify the _PACKET_BOUNDRY_TIME to 2000 or even a little less. If the individual bits are coming in faster than 10 microseconds that might be problem for the code.

Anyway, I think we've determined that there is some issues with the Airunit/googles/controller interaction which is changing the feed and its not my code. I will close out the issue.

**Comment by VermontCoder** [comment]
Issue was traced to developer's hardware acting weirdly, not the code.

**Comment by laszlojasko** [comment]
Hi!

I have found some clues what causes the code to be slow. Actually it is dropping a lot of frames. Do you use Logic2 from Saleae? I would get a capture file to show you the sbus packets that are coming from my receiver. I have been reading your code since then, but the math part with bits is pretty not easy to understand.

Saleae software can be downloaded for free, I use it on MacOS, but also ok for Linux or Windows. [Saleae Logic 2](https://www.saleae.com/downloads/)

I have an sbus packet analyzer for Saleae with source code that is reading the packet correctly if that helps you.

Will you help me, please?

**Comment by laszlojasko** [comment]
http://gofile.me/46v6w/CTFRJDxjg

I have uploaded a capture file. I added print() lines to you _sanity_check_packet method, and I get too many bad frames with current sanity checks.

I ger errors like:
Parity check failure (frame #6.0)   bitarray('111100100000')
UART start or stop bits bad (frame #8.0)   bitarray('011100111110')

Just every 5-10-15 packet is correct with current algorythm. Can you please improve it?

I found this packet analyzer to be working correctly with each packet. Can you please implement the packet reader with his algorythm?

https://github.com/pascalheude/Futaba-SBUS-protocol-decoder

**Comment by hhung516** [comment]
It's an old post but I needed sbus on a pi and ran into this exact issue. Spent quite some time trying different things in code but didn't really solve the delay.

So I ended up reading sbus using ESP32 and this [repo](https://github.com/bolderflight/sbus) and send the values to a pi via uart, works really well. I'm doing it at 10 hz which is enough for my need, but can probably push to 50 hz or even higher.
